Repository hmcts/send-letter-service, pull requests merged in 2019-11, with the labels that each got.

#602 Use jackson-databind from latest spring boot release
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe-send-letter-service-pr-602

#601 disable Legacy Deployment On ALL
  Jenkinsfile_CNP
Labels: ns:rpe-send-letter-service-pr-601

#603 delete ASE except demo
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rpe-send-letter-service-pr-603

#611 indent for new helm version
  charts/rpe-send-letter-service/values.preview.template.yaml
Labels: ns:rpe-send-letter-service-pr-611
