Repository hmcts/send-letter-service, pull requests merged in 2019-08, with the labels that each got.

#511 Bumped Jackson databind version to resolve CVE-2019-14379
  build.gradle
Labels: ns:rpe-send-letter-service-pr-511

#506 Remove unnecessary letter count metric in upload task
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
  src/test/java/uk/gov/hmcts/reform/sendletter/logging/AppInsightsTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
Labels: ns:rpe-send-letter-service-pr-506

#516 Update jenkins files for loading secrets
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  infrastructure/test_config.tf
Labels: ns:rpe-send-letter-service-pr-516

#518 Fix pipelines: PR, master
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  charts/rpe-send-letter-service/values.template.yaml
  infrastructure/output.tf
  src/main/resources/bootstrap.yaml
Labels: ns:rpe-send-letter-service-pr-518

#519 Fix pipeline db migration step
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
Labels: ns:rpe-send-letter-service-pr-519

#522 Remove output of `microserviceName`
  infrastructure/output.tf
Labels: ns:rpe-send-letter-service-pr-522
