Repository hmcts/send-letter-service, pull requests merged in 2019-04, with the labels that each got.

#354 Update spring to 2.1.4
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rpe-send-letter-service-pr-354

#352 Remove JUnit4
  build.gradle
Labels: ns:rpe-send-letter-service-pr-352

#355 Adjust cron for jobs related to csv files
  infrastructure/variables.tf
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-355

#358 Switch to `master` branch. Catch-up PR
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/variables.tf
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-358

#360 Adjust ftp downtime window
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-360

#363 Use latest (9.0.19) of embed tomcat
  build.gradle
Labels: ns:rpe-send-letter-service-pr-363

#365 Bump pdfbox 2.0.14 -> 2.0.15
  build.gradle
Labels: ns:rpe-send-letter-service-pr-365

#366 Update test dependencies
  build.gradle
Labels: ns:rpe-send-letter-service-pr-366

#367 Update gradle 5.3.1 -> 5.4
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rpe-send-letter-service-pr-367

#368 Use `Europe/London` timezone in tasks
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
  src/main/java/uk/gov/hmcts/reform/sendletter/util/TimeZones.java
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-368

#369 Update configuration for RestTemplate
  src/main/java/uk/gov/hmcts/reform/sendletter/config/RestTemplateConfiguration.java
  src/main/java/uk/gov/hmcts/reform/sendletter/config/ThreadPoolConfig.java
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-369

#371 Improve logging when marking letters as posted
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
Labels: ns:rpe-send-letter-service-pr-371

#372 Move `isSmokeTest` flag to model
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/FtpUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FileToSend.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
Labels: ns:rpe-send-letter-service-pr-372

#373 Include `ApacheHttpClient` for feign connections
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sendletter/config/RestTemplateConfiguration.java
Labels: ns:rpe-send-letter-service-pr-373

#374 Add more logging for uploading to ftp
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
Labels: ns:rpe-send-letter-service-pr-374

#375 Added liveness and alert action tf config
  infrastructure/alert_action_group.tf
  infrastructure/liveness-alert.tf
Labels: ns:rpe-send-letter-service-pr-375

#376 Add exception alert config
  infrastructure/exception-alert.tf
Labels: ns:rpe-send-letter-service-pr-376

#379 Fix AKS pipeline for PRs
  Jenkinsfile_CNP
Labels: ns:rpe-send-letter-service-pr-379

#378 BPS-626 Added reports end point for uploaded letters count
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ReportsController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LettersCountSummary.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/out/reports/LettersCountSummaryItem.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/out/reports/LettersCountSummaryResponse.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ReportsService.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/ReportsControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/rootcontroller/GetWelcomeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java
Labels: ns:rpe-send-letter-service-pr-378

#383 Update logging messages
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/encryption/PgpEncryptionUtil.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
Labels: ns:rpe-send-letter-service-pr-383

#382 BPS-626 Added repository layer for the report
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LettersCountSummaryRepositoryTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/LettersCountSummaryRepository.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/reports/ServiceLettersCount.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/reports/ServiceLettersCountSummary.java
Labels: ns:rpe-send-letter-service-pr-382
