Repository hmcts/send-letter-service, pull requests merged in 2019-09, with the labels that each got.

#531 Bump `checkstyle` to 8.24
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: ns:rpe-send-letter-service-pr-531

#523 Bump gradle 5.5.1 -> 5.6.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:rpe-send-letter-service-pr-523

#532 Clean up env settings
  infrastructure/aat.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:rpe-send-letter-service-pr-532

#533 Bump commons-compress 1.18 -> 1.19
  build.gradle
Labels: ns:rpe-send-letter-service-pr-533

#538 Remove 'dynamic' version of flyway from `versions` definition
  build.gradle
Labels: ns:rpe-send-letter-service-pr-538

#540 Use of `moj` prefix is deprecated
  infrastructure/main.tf
Labels: ns:rpe-send-letter-service-pr-540

#547 Split out user auth related IOException for better debug
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/FtpClientTest.java
Labels: ns:rpe-send-letter-service-pr-547

#549 Suppress not yet released jackson-databind fix
  config/owasp/suppressions.xml
Labels: ns:rpe-send-letter-service-pr-549

#548 Bump shedlock 2.5.0 -> 3.0.0
  build.gradle
Labels: ns:rpe-send-letter-service-pr-548

#552 Bump jackson-databind 2.9.9.3 -> 2.9.10
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe-send-letter-service-pr-552

#555 Update test dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe-send-letter-service-pr-555

#557 Remove filtering letters by encryption key fingerprint
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
  src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
Labels: ns:rpe-send-letter-service-pr-557

#558 Update rest of dependencies
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rpe-send-letter-service-pr-558

#559 Increase max wait time for files to appear on FTP in functional tests
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
  src/functionalTest/resources/application.properties
Labels: ns:rpe-send-letter-service-pr-559

#560 Remove no longer needed config
  infrastructure/main.tf
  infrastructure/variables.tf
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-560
