Repository hmcts/send-letter-service, pull requests merged in 2019-07, with the labels that each got.

#475 Update scheduled jobs config format
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndWithEncryptionEnabledTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/StaleLettersTask.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-475

#476 Filter letters by fingerprint when uploading
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTask.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
Labels: ns:rpe-send-letter-service-pr-476

#478 Clean up end-to-end test assertions
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
Labels: ns:rpe-send-letter-service-pr-478

#477 Update the diagram
  doc/arch/diagram.drawio
  doc/arch/diagram.png
  doc/arch/diagram.xml
  doc/arch/readme.md
Labels: ns:rpe-send-letter-service-pr-477

#479 Enable encryption on AAT
  infrastructure/aat.tfvars
Labels: ns:rpe-send-letter-service-pr-479

#481 Filter letters on aat by fingerprint
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rpe-send-letter-service-pr-481

#442 Cleanup vault/secret configuration
  infrastructure/alert_action_group.tf
  infrastructure/main.tf
  infrastructure/test_config.tf
Labels: ns:rpe-send-letter-service-pr-442

#486 Added subscripition var to db module as it is mandatory going forward
  infrastructure/main.tf
Labels: ns:rpe-send-letter-service-pr-486

#487 Adding service folder for financial remedy (#FR-862)
  src/main/resources/application.yaml
Labels: ns:rpe-send-letter-service-pr-487

#491 Hotfix `jackson-databind` 2.9.9 -> 2.9.9.1
  build.gradle
Labels: ns:rpe-send-letter-service-pr-491

#499 Update downtime window for helm chart (used in PRs)
  charts/rpe-send-letter-service/Chart.yaml
  charts/rpe-send-letter-service/values.template.yaml
Labels: ns:rpe-send-letter-service-pr-499

#497 Update Dockerfile to use image from new place
  Dockerfile
Labels: ns:rpe-send-letter-service-pr-497

#441 Review FTP client method calls
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/FtpUploadTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/logging/DependencyCommand.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
Labels: ns:rpe-send-letter-service-pr-441, pinned

#498 Provide letter ID in functional test assertion exception
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
Labels: ns:rpe-send-letter-service-pr-498

#492 Update test dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe-send-letter-service-pr-492

#500 Don't load full letter when marking as `Posted`
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterDataAccessService.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTest.java
Labels: ns:rpe-send-letter-service-pr-500

#459 Unwrap list ftp files function in `FtpClient`
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTask.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/DeleteOldFilesTaskTest.java
Labels: ns:rpe-send-letter-service-pr-459

#502 Remove overlapped integration test
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/FtpUploadTest.java
Labels: ns:rpe-send-letter-service-pr-502

#503 Update all dependencies but bouncycastle
  build.gradle
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rpe-send-letter-service-pr-503

#504 Bump bouncycastle 1.61 -> 1.62
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe-send-letter-service-pr-504

#505 Use Helm charts from hmctspublic repository
  charts/rpe-send-letter-service/Chart.yaml
  charts/rpe-send-letter-service/requirements.yaml
Labels: ns:rpe-send-letter-service-pr-505
