Repository hmcts/send-letter-service, pull requests merged in 2020-08, with the labels that each got.

#775 DTSBP-34: Remove requirement for service authentication from the get…
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LetterTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
  src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/UnauthorisedSmokeTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/GetLetterStatusControllerTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-775

#778 DTBSP-20: Fix docker sftp
  README.md
  docker-compose.yml
  docker/env.list
  docker/sftp/Dockerfile
  docker/sftp/data/SMOKE_TEST/.gitignore
  docker/sftp/data/incoming/.gitgnore
  docker/sftp/data/keys/sftp-docker.pub
  docker/sftp/keys/keypair
  docker/sftp/keys/keypair.pub
  docker/sftp/keys/ssh_host_ed25519_key
  docker/sftp/keys/ssh_host_ed25519_key.pub
  docker/sftp/keys/ssh_host_rsa_key
  docker/sftp/keys/ssh_host_rsa_key.pub
  src/functionalTest/resources/application.properties
  src/smokeTest/resources/application.properties
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-778

#777 DTSBP-35: publish swagger docs
  Jenkinsfile_CNP
  docker/sftp/data/incoming/BULKPRINT/.gitignore
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-777

#780 DTBSP-20: Fix environment variable format for linux
  docker/env.list
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-780

#783 DTBSP-20: Move keys to compose file, and change the way incoming dire…
  docker-compose.yml
  docker/env.list
  docker/sftp/Dockerfile
  docker/sftp/data/SMOKE_TEST/.gitignore
  docker/sftp/data/incoming/BULKPRINT/.gitignore
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-783

#784 DTBSP-35: use non standard ftp port to prevent conflict on jenkins
  docker-compose.yml
  src/functionalTest/resources/application.properties
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-784

#786 Switch to github action to publish swagger docs
  .github/workflows/swagger.yaml
  Jenkinsfile_CNP
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-786

#792 DTSBP-7: Add comments for additionalData in documentation
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterRequest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsAndNumberOfCopiesRequest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsRequest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-792

#795 DTSBP-18: deprecate the api which accepts templates and data
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
  src/functionalTest/resources/letter_single_document.json
  src/functionalTest/resources/letter_two_documents.json
  src/functionalTest/resources/one-page-template.html
  src/functionalTest/resources/two-page-template.html
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndWithEncryptionEnabledTest.java
  src/integrationTest/resources/letter.json
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterController.java
  src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/CreateLetterSmokeTest.java
  src/smokeTest/resources/letter-with-document-count.json
  src/smokeTest/resources/letter-with-pdf.json
  src/smokeTest/resources/letter.json
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
  src/test/resources/controller/letter/v1/letter-with-multiple-docs.json
  src/test/resources/controller/letter/v1/letter-without-doc.json
  src/test/resources/controller/letter/v1/letter-without-template-values.json
  src/test/resources/controller/letter/v1/letter-without-template.json
  src/test/resources/controller/letter/v1/letter-without-type.json
  src/test/resources/controller/letter/v1/letter.json
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-795

#800 DTBSP-44: spring boot and chart upgrade
  build.gradle
  charts/rpe-send-letter-service/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-800

#803 DTBSP-50: Bump flyway-core from 6.5.3 to 6.5.5
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-803

#805 Remove unused tf remote state
  infrastructure/state.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-805
