Repository hmcts/send-letter-service, pull requests merged in 2020-07, with the labels that each got.

#746 Upgraded to Java 11
  Dockerfile
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-746

#747 Upgrade gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-747

#751 Bumped wiremock version and removed handlebars vulnerability suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-751

#752 Bump tomcat 9.0.35 -> 9.0.37
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-752

#756 Fix vulnerability reported by owasp
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-756

#755 Remove infra config for main app
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-755

#758 Revert "Remove infra config for main app"
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-758

#757 Feature: postgres v11 database(s)
  infrastructure/main.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-757

#760 Add new db (v11) configs
  charts/rpe-send-letter-service/Chart.yaml
  charts/rpe-send-letter-service/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-760

#763 Use new optional method
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/MarkLettersPostedTask.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-763

#764 Add repo method for deleting file content of old letters
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/ClearFileContentTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/LetterRepository.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-764

#765 Add scheduled job for clearing content of old letters
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTask.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTaskTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-765

#766 Fix docker-compose command in readme
  README.md
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-766

#767 Update slack notification channel
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-767

#770 Use service layer when clearing letter content
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterDataAccessService.java
  src/main/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTask.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/ClearOldLetterContentTaskTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-770
