Repository hmcts/send-letter-service, pull requests merged in 2020-02, with the labels that each got.

#643 Remove deprecated flag of docker build
  Jenkinsfile_CNP
Labels: ns:rpe, rel:rpe-send-letter-service-pr-643

#644 Upgrade checkstyle
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: ns:rpe, rel:rpe-send-letter-service-pr-644

#645 Fpla onboarding
  src/main/resources/application.yaml
Labels: ns:rpe, rel:rpe-send-letter-service-pr-645

#647 Remove redundant dependency management for tomcat
  build.gradle
Labels: ns:rpe, rel:rpe-send-letter-service-pr-647

#656 Bump org.springframework.boot from 2.2.4.RELEASE to 2.2.5.RELEASE and remove deprecated chart config
  build.gradle
  charts/rpe-send-letter-service/Chart.yaml
  charts/rpe-send-letter-service/requirements.yaml
  charts/rpe-send-letter-service/values.preview.template.yaml
  config/owasp/suppressions.xml
Labels: ns:rpe, rel:rpe-send-letter-service-pr-656
