Repository hmcts/send-letter-service, pull requests merged in 2020-05, with the labels that each got.

#700 Bump log4j 2.12.1 -> 2.13.2
  build.gradle
Labels: ns:rpe, rel:rpe-send-letter-service-pr-700

#696 Use send letter MI instead of generic RPE MI
  infrastructure/demo.tfvars
Labels: ns:rpe, rel:rpe-send-letter-service-pr-696

#705 Update dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, rel:rpe-send-letter-service-pr-705

#708 Add infrastructure for staging database
  infrastructure/main.tf
Labels: ns:rpe, rel:rpe-send-letter-service-pr-708

#709 Remove deprecated configuration
  Jenkinsfile_CNP
Labels: ns:rpe, rel:rpe-send-letter-service-pr-709

#710 Add staging db secrets to bootstrap config
  charts/rpe-send-letter-service/values.aat.template.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:rpe, rel:rpe-send-letter-service-pr-710

#712 Set flyway migration skipping to false so that app runs it
  charts/rpe-send-letter-service/values.aat.template.yaml
Labels: ns:rpe, rel:rpe-send-letter-service-pr-712
