Repository hmcts/send-letter-service, pull requests merged in 2021-07, with the labels that each got.

#1169 DTSBPS-653: Bump greenmail from 1.5.13 to 1.6.4
  build.gradle
  src/test/java/uk/gov/hmcts/reform/sendletter/jupiter/GreenMailExtension.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1169

#1172 DTSBPS-267: sync with master
  Jenkinsfile_CNP
  infrastructure/ithc.tfvars
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1172

#1173 DTSBPS-661: code compliance security hotspot
  src/main/java/uk/gov/hmcts/reform/sendletter/util/CsvWriter.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/PendingLettersControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsAndCopiesControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/StaleLetterServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/date/DateCalculatorTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/date/holidays/BankHolidaysClientTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1173

#1174 Upgrade gradle 7 1 1
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/smokeTest/java/uk/gov/hmcts/reform/sendletter/controllers/SmokeTestSuite.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1174

#1180 Fix folder setup of nfdiv_case_api service
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1180

#1183 upgrade libs
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1183

#1188 DTSBPS-674: functional test for async call
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1188

#1189 DTSBPS-677: bumping lib
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1189

#1191 DTSBPS-681: fix - intermittent integration test failure
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1191

#1199 DTSBPS-682: fix - unstable google load resource
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/PrintLetterControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsAndCopiesControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/SendLetterWithPdfsControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/model/in/print/PrintRequestTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/DuplicateLetterServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/ExceptionLetterServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/PdfMergerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/ReportParserTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/FinalPackageFileNameHelperTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/zip/ZipperTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/PendingLettersTaskTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/tasks/alerts/StaleLettersTaskTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/util/ResourceLoader.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1199

#1201 DTSBPS-681: fix - unstable test
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/EndToEndWithEncryptionEnabledTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1201

#1205 adding log message
  src/main/java/uk/gov/hmcts/reform/sendletter/services/PrintService.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1205

#1207 DTSBPS-686: adding fod scan on nightly pipeline
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1207

#1208 DTSBPS-686: adding fod scan on nightly pipeline
  Jenkinsfile_nightly
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1208

#1209 Pass vault name explicitly to fortify function
  Jenkinsfile_nightly
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1209

#1210 DTSBPS-686: adding fod scan on nightly pipeline
  Jenkinsfile_nightly
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1210

#1211 DTSBPS-686: adding fod scan on nightly pipeline
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1211

#1212 DTSBPS-691: update chart java version
  charts/rpe-send-letter-service/Chart.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1212

#1213 Grant access to AAT SA from preview env
  infrastructure/preview_vnet.tf
  infrastructure/storage-account.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1213
