Repository hmcts/send-letter-service, pull requests merged in 2021-12, with the labels that each got.

#1337 Dtsbps 807 upgrade spring boot 2.6.1
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/ApplicationTest.java
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/sendletter/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/PrintLetterController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/PendingLettersController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/ReportsController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/Document.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterRequest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsAndNumberOfCopiesRequest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/LetterWithPdfsRequest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/PrintRequest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatus.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/out/SendLetterResponse.java
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1337

#1345 Bump log4j version
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1345

#1351 Updated fortify release id
  config/fortify-client.properties
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1351
