Repository hmcts/send-letter-service, pull requests merged in 2021-11, with the labels that each got.

#1309 DTSBPS-773: fix spring cve error
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1309

#1310 DTSBPS-775: fix spring cve error
  build.gradle
  infrastructure/data.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1310

#1316 DTSBPS-782 add BSP slack notification channel
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1316

#1317 DTSBPS-784 Fix dependency management
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
  src/integrationTest/resources/docker/docker-compose.yml
  src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1317
