Repository hmcts/send-letter-service, pull requests merged in 2021-01, with the labels that each got.

#941 DTSBPS-291: Drop columns of Duplicate table
  charts/rpe-send-letter-service/values.preview.template.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/DuplicateLetterTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/DuplicateLetter.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
  src/main/resources/db/migration/V022__Drop columns of Duplicate table
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-941

#943 DTSBPS-291: Renamed script to V022__Drop_columns_of_duplicate_table
  src/main/resources/db/migration/V022__Drop_columns_of_duplicate_table.sql
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-943

#950 DTSBPS-298: Fixing build
  charts/rpe-send-letter-service/values.preview.template.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-950

#951 DTSBPS-298: Fixing pact test failure
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-951

#952 DTSBPS-298: Fixing pact test failure
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-952

#953 DTSBPS-298: Fixing pact test failure
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-953

#954 Add no fault divorce API to config
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-954

#946 Add ADR to docs
  README.md
  doc/arch/adr/0001-increase-pod-memory-for-oom-error.md
  doc/arch/readme.md
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-946

#960 DTSBPS-298: Fixing pdfbox version
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-960

#966 DTSBPS-320: Fixing sshd libraries
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LocalSftpServer.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-966
