Repository hmcts/send-letter-service, pull requests merged in 2021-06, with the labels that each got.

#1125 DTSBPS-579: Send letter Service Incorporate PDF generator library cha…
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceWithEncryptionEnabledTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PdfCreatorTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/tasks/UploadLettersTaskTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/config/PdfConversionConfig.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1125

#1126 DTSBPS-618:nf-divorce service name correction
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1126

#1127 Dtsbps 621 bump libraries
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1127

#1142 DTSBPS-626: fix spring-vulnerabilities
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1142

#1152 DTSBPS-632: bumped gradel version 6.8.3
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1152

#1154 DTSBPS-632: spring boot upgrade to 2.5.1
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1154

#1157 Sonar project name
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1157

#1161 bump libs
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1161
