Repository hmcts/send-letter-service, pull requests merged in 2022-01, with the labels that each got.

#1367 Bump com.github.ben-manes.versions from 0.40.0 to 0.41.0
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1367

#1380 Bumped org.owasp.dependencycheck 6.5.2.1 to 6.5.3, shedlock-provider-…
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1380

#1395 DTSBPS-857 fix vnet
  infrastructure/data.tf
  infrastructure/storage-account.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1395

#1396 DTSBPS-857 remove app_gw subnet
  infrastructure/data.tf
  infrastructure/storage-account.tf
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1396
