Repository hmcts/send-letter-service, pull requests merged in 2022-05, with the labels that each got.

#1494 DTSBPS-903: add tags to send-letter resource group and appinsights
  infrastructure/appinsights.tf
  infrastructure/main.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1494

#1495 DTSPO-8293 - Update ithc storage account to ZRS
  infrastructure/ithc.tfvars
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1495

#1518 Update fingerprint
  Jenkinsfile_CNP
  build.gradle
  charts/rpe-send-letter-service/Chart.yaml
  charts/rpe-send-letter-service/values.yaml
  infrastructure/variables.tf
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/FunctionalTestSuite.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1518

#1522 Suppress CVE-2022-29885 (DTSBPS-947)
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1522

#1535 DTSBPS-956: Fix secret scanning
  src/integrationTest/resources/application.properties
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1535
