Repository hmcts/send-letter-service, pull requests merged in 2022-09, with the labels that each got.

#1745 DTSBPS-1067: Fix CVE-2022-25857
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1745

#1747 Add an endpoint to mark letters as posted (DTSBPS-1065)
  src/main/java/uk/gov/hmcts/reform/sendletter/ResponseExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/ActionController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/EventType.java
  src/main/java/uk/gov/hmcts/reform/sendletter/exception/UnableToMarkLetterPostedException.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterActionService.java
  src/test/java/uk/gov/hmcts/reform/sendletter/controllers/sendlettercontroller/ActionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterActionServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1747

#1751 Fix Null Pointer Exception in MarkLetterAsPosted task
  src/main/java/uk/gov/hmcts/reform/sendletter/logging/AppInsights.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1751

#1761 Configuration to enable or disable services (DTSBPS-1069)
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/LetterUploadForDisabledServiceTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/services/LetterServiceTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/config/FtpConfigProperties.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1761

#1752 updated standard subnets to include new cft prod aks cluster
  infrastructure/data.tf
  infrastructure/storage-account.tf
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-1752

#1783 DTSBPS-1083: Added suppression
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1783

#1787 Add config for civil-service (DTSBPS-1079)
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1787

#1788 Update service name for civil-service (DTSBPS-1079)
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1788

#1793 Fix PendingLetters tests (DTSBPS-1088)
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/PendingLetterSearchTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/PendingLettersServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1793

#1797 Add app-insights connection string (DTSBPS-1090)
  infrastructure/appinsights.tf
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-1797

#1798 Add secret for app-insights connection string
  charts/rpe-send-letter-service/Chart.yaml
  charts/rpe-send-letter-service/values.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1798

#1795 DTSBPS-1091: Upgrade pact version
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1795
