Repository hmcts/send-letter-service, pull requests merged in 2022-02, with the labels that each got.

#1398 grants access to storage account from perftest mgmt subnet
  infrastructure/perftest_mgmt_subnet.tf
  infrastructure/provider.tf
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1398

#1407 Fix vulnerability
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1407

#1410 Bump java chart
  charts/rpe-send-letter-service/Chart.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1410
