Repository hmcts/send-letter-service, pull requests merged in 2022-04, with the labels that each got.

#1470 Suppress vulnerabilities
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1470

#1483 Vulnerability suppress
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1483

#1372 DTSPO-5822 - ZRS Migration
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: DO NOT MERGE, ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1372
