Repository hmcts/send-letter-service, pull requests merged in 2022-10, with the labels that each got.

#1812 Suppress CVE 2022 33915
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1812

#1799 Upgrade java and appinsights (DTSBPS-1090)
  Dockerfile
  build.gradle
  config/checkstyle/checkstyle.xml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/contractTest/java/uk/gov/hmcts/reform/sendletter/controllers/SendLetterProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/FailingUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/e2e/LetterUploadForDisabledServiceTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/LettersFromGivenDaySearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/PendingLetterSearchTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/controllers/reports/StaleLetterController.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/PrintServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1799

#1814 Fix scala-library vulnerability (DTSBPS-1105)
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1814

#1816 Revert "Bump postgresql from 1.17.4 to 1.17.5"
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1816

#1818 Suppress CVE-2022-42003 and CVE-2022-42004 (DTSBPS-1109)
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1818

#1828 DTSBPS-1118: Removed old cluster subnets
  infrastructure/data.tf
  infrastructure/storage-account.tf
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-1828

#1831 Update Old files deletion TTL (DTSBPS-1108)
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1831

#1847 DTSBPS-1127: Suppressed CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1847

#1852 Update civil service config (DTSBPS-1135)
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1852

#1853 Update civil service config (DTSBPS-1135)
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1853
