Repository hmcts/send-letter-service, pull requests merged in 2023-03, with the labels that each got.

#2136 DTSBPS-1325: Fix CVE 2023 24998
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2136

#2145 DTSBPS-1329: Fix CVE 2022 29523
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2145

#2144 DTSBPS-1322: added documents table sql
  src/main/resources/db/migration/V025__Add_documents_table.sql
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2144

#2154 DTSBPS-1322: repository layer
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/entity/DocumentRepositoryTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/Document.java
  src/main/java/uk/gov/hmcts/reform/sendletter/entity/DocumentRepository.java
  src/main/resources/db/migration/V026__Alter_documents_table_id_column_type.sql
  src/test/java/uk/gov/hmcts/reform/sendletter/SampleData.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2154

#2155 DTSBPS-1322: added document service
  src/main/java/uk/gov/hmcts/reform/sendletter/exception/DuplicateDocumentException.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/DocumentService.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterChecksumGenerator.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/DocumentServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2155

#2102 changes for resilience + local dev
  .gitignore
  build.gradle
  docker-compose.yml
  docker/database/Dockerfile
  docker/database/init-db.sh
  src/main/resources/application.yaml
Labels: DO NOT MERGE, ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-2102
