Repository hmcts/send-letter-service, pull requests merged in 2023-05, with the labels that each got.

#2273 Private law onboarding
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2273

#2288 FACT-1386 copies data to be returned in GET /letters/<id> endpoint
  src/integrationTest/java/uk/gov/hmcts/reform/sendletter/controllers/GetLetterStatusTest.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/out/ExtendedLetterStatus.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/out/LetterStatus.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterService.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2288

#2296 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2296

#2304 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2304

#2315 updating cves
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-2315
