Repository hmcts/send-letter-service, pull requests merged in 2023-01, with the labels that each got.

#1993 DTSBPS-1231: Suppresed CVE-2022-45693, CVE-2022-45685
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-1993

#2005 DTSBPS-1235: Fix CVE 2021 4277
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2005

#2011 DTSBPS-1236: Fix CVE 2022 31692
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2011

#2013 DTSBPS-1234 Update actions endpoint
  src/main/java/uk/gov/hmcts/reform/sendletter/services/LetterActionService.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/LetterActionServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2013

#2049 DTSBPS-1276: cleanup suppressions
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2049
