Repository hmcts/send-letter-service, pull requests merged in 2024-08, with the labels that each got.

#2582 Send letter sftp 3
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  docker/sftp/Dockerfile
  docker/sftp/README.md
  docker/sftp/keys/keypair
  docker/sftp/keys/keypair.pub
  docker/sftp/keys/ssh_host_ed25519_key
  docker/sftp/keys/ssh_host_ed25519_key.pub
  docker/sftp/keys/ssh_host_rsa_key
  docker/sftp/keys/ssh_host_rsa_key.pub
  docker/sftp/sftp.json
  docker/sftp/ssh/id_dev_rsa.pub
  docker/sftp/ssh/id_dev_rsa.txt
  docker/sftp/ssh/id_ed25519.pub
  docker/sftp/ssh/id_ed25519.txt
  docker/sftp/ssh/id_rsa.pub
  docker/sftp/ssh/id_rsa.txt
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/sendletter/services/ftp/FtpClient.java
  src/main/resources/application-dev.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2582

#2583 Appinsights fix
  Dockerfile
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2583

#2578 FACT-1906 dependancy updates
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2578

#2600 app insights terraform fix
  README.md
  infrastructure/appinsights.tf
Labels: ns:rpe, prd:rpe, aat/add-or-update, prod/add-or-update, rel:rpe-send-letter-service-pr-2600
