Repository hmcts/send-letter-service, pull requests merged in 2024-03, with the labels that each got.

#2484 FACT-1632 switch to use flex creds
  charts/rpe-send-letter-service/Chart.yaml
  charts/rpe-send-letter-service/values.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2484

#2485 Fix build
  infrastructure/state.tf
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-2485

#2487 Update AAT to use flexi stg DB
  charts/rpe-send-letter-service/values.aat.template.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2487

#2503 Fix dependancies ahead of release
  README.md
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2503

#2500 Force user permissions on DB [DO NOT MERGE UNTIL RELEASE]
  infrastructure/tf-db-flexible.tf
Labels: ns:rpe, prd:rpe, destroy, rel:rpe-send-letter-service-pr-2500

#2505 Temp disable func tests & db product change
  infrastructure/tf-db-flexible.tf
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-2505

#2506 Updated storage to use 128gb in prod
  infrastructure/prod.tfvars
  infrastructure/tf-db-flexible.tf
  infrastructure/variables.tf
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-2506

#2507 Update storage space db
  infrastructure/prod.tfvars
  infrastructure/tf-db-flexible.tf
  infrastructure/variables.tf
Labels: ns:rpe, prd:rpe, add-or-update, rel:rpe-send-letter-service-pr-2507

#2508 Re-enable func tests
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpoint.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageTestForPdfEndpointV2Async.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessMessageWithDocumentCountTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sendletter/ProcessSaveV3Asyn.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-pr-2508
